version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_db_${PROJECT_NAME}
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    container_name: redis_${PROJECT_NAME}
    networks:
      - portfolio_network

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: django_web_${PROJECT_NAME}
    command: sh -c "/entrypoint.sh && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ../app:/app
      - ../app/static:/app/static
      - ../app/media:/app/media
    env_file:
      - ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    networks:
      - portfolio_network

  telegram_bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: telegram_bot_${PROJECT_NAME}
    command: python manage.py bot
    volumes:
      - ../app:/app
    env_file:
      - ../.env
    depends_on:
      - db
      - web
    networks:
      - portfolio_network

networks:
  portfolio_network:
    driver: bridge

volumes:
  postgres_data:
