version: '3.8'

services:
  db_${PROJECT_NAME}:
    image: postgres:14
    container_name: postgres_db_${PROJECT_NAME}
    env_file:
      - ../.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_${PROJECT_NAME}:
    image: redis:6
    container_name: redis_${PROJECT_NAME}
    ports:
      - "6389:6379"
    networks:
      - portfolio_network

  web_${PROJECT_NAME}:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: django_web_${PROJECT_NAME}
    command: sh -c "/entrypoint.sh && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8082"
    volumes:
      - ../app:/app
      - ../app/static:/app/static
      - ../app/media:/app/media
    env_file:
      - ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.dev
    depends_on:
      db_${PROJECT_NAME}:
        condition: service_healthy
      redis_${PROJECT_NAME}:
        condition: service_started
    ports:
      - "127.0.0.1:8084:8082"
    networks:
      - portfolio_network

  telegram_bot_${PROJECT_NAME}:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: telegram_bot_${PROJECT_NAME}
    command: python manage.py bot
    volumes:
      - ../app:/app       # исправлено
    env_file:
      - ../.env
    depends_on:
      - db_${PROJECT_NAME}
      - web_${PROJECT_NAME}
    networks:
      - portfolio_network

networks:
  portfolio_network:
    driver: bridge

volumes:
  postgres_data:
